---
hero_image: images/special-effects.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Special Effects
description: Create special effects for a film or computer game.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/special-effects
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Suspense
  - 
    title: Stormy night
    completion:
      - engaged
  - 
    title: Haunted bells
    completion:
      - internal
  - 
    title: 'Challenge: Create your own special effects'
