---
hero_image: images/special-effects.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Spezialeffekte
description: Erstellen Sie Spezialeffekte für einen Film oder ein Computerspiel.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/special-effects
interests: musik
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Spannung
  - 
    title: Stürmische Nacht
  - 
    title: Geisterglocken
  - 
    title: 'Herausforderung: Erstellen Sie Ihre eigenen Spezialeffekte'
