---
hero_image: images/special-effects.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programmering-1, phys-comp-0, tillverkning-0, community-0
title: Special Effects
description: Create special effects for a film or computer game.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/special-effects
interests: musik
technologies: ''
site_areas: projekt
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Introduktion
  - 
    title: Suspense
  - 
    title: Stormy night
  - 
    title: Haunted bells
  - 
    title: 'Challenge: Create your own special effects'
