---
hero_image: images/special-effects.png
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Effets spéciaux
description: Créer des effets spéciaux pour un film ou un jeu vidéo.
original_url: https://codeclubprojects.org/en-GB/sonic-pi/special-effects
interests: music
technologies: ''
site_areas: projects
hardware: ''
software: ''
version: 3
last_tested: 2017-01-01
steps:
- title: Introduction
  completion: engaged
- title: Suspense
- title: Nuit orageuse
- title: Cloches hantées
  completion: internal
- title: 'Défi : créer tes propres effets spéciaux'
